version: "3.7"

services:
  demo-api:
    image: demo-api:${VERSION:-development}
    container_name: demo-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
